textIoVersionMajor = 3
textIoVersionMinor = 4
textIoVersionPatch = 2
textIoVersionLabel=GIOLEG-3
textIoReleaseBuild=true

#Artifactory
artifactory_user=service-synergy
artifactory_password=SynergyArtifactory
artifactory_contextUrl=https://local-artifactorypro.sanmarcoweb.com:443/artifactory
artifactory_repo=synergy-dev-v
artifactory_repo_publish=synergy-dev-local
